module SelectSolver

# This module contains the functions get_params(...) and solve(...).
# The function get_params(...) reads the params.jl file and returns the params tuple.
# The function solve(...) reads the data and settings tuples and returns the solution tuple.
# The params tuple contains the parameters (defined in the file params.jl) of the selected solver.
# The settings and data tuples are properly described in the ImportSettings and ImportData modules.
# The solution tuple contains the solution of the optimization (generated by the optimization
# solver called from solve(...)), which is composed of: (1) a vector containing the run
# (optimization cycle) number, (2) a vector containing the energy of the best ion distribution
# found in each run, and (3) a vector of vectors containing the best ion distribution found in each
# run. An example of how this tuple is generated can be found in the SANSS_set(...) function of
# the SANSS module.
# 
# note:
# Each solver must be defined in its file in the SOLVERS subdirectory.
# The file must contain a module, and within the module, all the functions necessary for the solver
# must be defined.
# The only requirement for each solver is that its main function must take the data and params
# tuples as arguments, and returns the solution tuple.
# If a new solver is implemented, the module must be loaded in the "load solvers" section, and a
# new statement must be added in the get_params(...) and solve(...) function.

# load Julia modules
using UnPack
using MutableNamedTuples

# load solvers
include("SOLVERS/SANSS.jl")
using .SANSS

function get_params(solver::String)

    # This function generates a params tuple for the selected solver.
    # The params tuple contains the parameters defined in the params.jl file.
    # Since different solvers use different parameters, for each new solver defined in the
    # SOSS package, a new instance must be added below (currently, only SANSS is defined).
    # Arguments:
    # solver -----> String containing the name of the optimization solver.
    #
    # Returns:
    # params -----> Tuple containing the parameters of the optimization solver.

    if solver == "SANSS"
        params = (
            IT_scheme = IT_scheme::Int64,
            IT_params = IT_params::Vector{Float64},
            tempLength = tempLength::Int64,
            beta = beta::Float64,
            scheme = scheme::String,
            gamma = gamma::Int64,
            ScanningStyle = ScanningStyle::Int64,
            FirstToImprove = FirstToImprove::Bool,
            steps = steps::Int64,
            MaxStagnation = MaxStagnation::Int64,
            nRepeats = nRepeats::Int64,
            DisplayStyle = DisplayStyle::Int64,
            plots = plots::Bool
        )
    end
    return params
end

function solve(data::NamedTuple, settings::NamedTuple)

    # This function reads the data and setting tuples, solves the problem using the selected
    # solver and returns the solution tuple.
    #
    # Arguments:
    # data -----> tuple containing the structural and energetic data of the system.
    # settings -> tuple containing the settings tags.
    #
    # Returns:
    # solution -> tuple containing the solution of the optimization problem.

    @unpack solver = settings

    println(" ")
    println("-------------------------------------------------------------------------------------------------")
    println("   START STRUCTURE OPTIMIZATION")
    println("-------------------------------------------------------------------------------------------------")
    println("SOLVER: $solver\n")
    if solver == "SANSS"
        params = get_params(solver)
        solution = SANSS.SANSS_set(data, params)
    else
        println("ERROR: INCORRECT SOLVER")
    end
    println("-------------------------------------------------------------------------------------------------")
    println("   END STRUCTURE OPTIMIZATION")
    println("-------------------------------------------------------------------------------------------------")

    return solution

end

end