module ExportData

# This module contains the necessary functions to read the output from the optimizers and write
# an atomic structure file in the desired format.
# Note: Currently, only VASP format (POSCAR) is available.

using UnPack
using Printf

function get_structure(data::NamedTuple, solution::Vector{Int64})

    # This function reads the tupple generated by the get_data(...) function (defined in
    # ImportData.jl) and the output from the optimizer (vector containing the sites that have
    # been occupied by the ions) and returns the final composition (chemical symbols) of the
    # structure and the positions of the atoms.
    #
    # Arguments:
    # data -----> Tupple containing the system information (explained in the ImportData module).
    # solution -> Vector containing the site ID that each ion occupies in the final
    #             structure.
    #
    # Returns:
    # composition ----> Vector of vectos, where each subvector contains (1st element) the chemical 
    #                   symbol of each specie in the final structure and (2nd element) the
    #                   number of atoms of that specie in the final structure.
    # FinalPositions -> Matrix containing the xyz position of each atom in the final
    #                   structure.

    @unpack symbols, species, Ions, SIons, LIons, Na, positions = data

    L = sum(Int64, LIons)

    composition = []
    i = 1
    for specie in species
        if specie ∉ SIons
            num = length(findall(x->x==specie,symbols))
            push!(composition, [specie, num])
            i += 1
        end
    end
    for ion in Ions
        push!(composition, [SIons[ion], LIons[ion]])
    end
    
    FinalPositions = Matrix{Float64}(undef,Na,3)
    i = 1
    for compound in composition
        symbol = compound[1]
        number = compound[2]
        if symbol ∉ SIons
            sites  = findall(x->x==symbol,symbols)
            FinalPositions[i:i+number-1,:] = positions[sites,:]
            i += number
        end
    end
    for j = 1:L
        site = solution[j]
        FinalPositions[i,:] = positions[site,:]
        i += 1
    end

    return composition, FinalPositions
end

function WritePoscar(lattice,composition,positions,file)

    # This function reads the lattice vectors, the composition (generated by get_structure()), the
    # positions of the atoms and the file name of the output optimal structure and generates the
    # output atomic structure file in VASP format (POSCAR)
    #
    # Arguments:
    # lattice -----> 2D array (3x3) containing the lattice vectors (floats) of the final structure.
    # composition -> Vector of vectos, where each subvector contains (1st element) the chemical 
    #                symbol of each specie in the final structure and (2nd element) the
    #                number of atoms of that specie in the final structure.
    # positions ---> Matrix containing the xyz position of each atom in the final structure.
    # file --------> Name of the output structure file.
    #
    # Returns:
    # No returns.

    file = open(file, "w")
    write(file, " ")
    write(file, "\n1.0 \n")
    for i = 1:3
        write(file, "$(lattice[i,1]) $(lattice[i,2]) $(lattice[i,3])\n")
    end
    write(file, "")
    for compound in composition
        write(file, "$(compound[1]) ")
    end
    write(file, "\n")
    for compound in composition
        write(file, "$(compound[2]) ")
    end
    write(file, "\nCartesian\n")
    for i in eachindex(positions[:,1])
        write(file, "$(positions[i,1]) $(positions[i,2]) $(positions[i,3])\n")
    end
    close(file)
end

function save_structure(data::NamedTuple, solution::NamedTuple, settings::NamedTuple)

    # This function reads the data tupple generated by the get_data(...) function (defined in
    # ImportData.jl), the solution tupple generated by the solve(...) function (defined in
    # Solvers.jl) and the settings tupple generated by get_settings(...) (defined in
    # ImpotSettings.jl), and writes the structure file of the final structure (after optimization)
    # in the format defined in the settings file.
    #
    # Arguments:
    # data -----> Tupple containing the system information (explained in the ImportData module).
    # solution -> Vector containing the site ID that each ion occupies in the final
    #             structure.
    # settings -> Tupple containing the settings information (explained in the ImpotSettings
    #             module).
    #
    # Returns:
    # No retuns.


    @unpack lattice = data
    @unpack runs, configs = solution
    @unpack OUT_format = settings

    mkdir("STRUCTURES")

    println(" ")
    println("-------------------------------------------------------------------------------------------------")
    println("   START EXPORT DATA")
    println("-------------------------------------------------------------------------------------------------")
    for i in eachindex(runs)
        run = runs[i]
        config = configs[i]
        composition, FinalPositions = get_structure(data, config)

        if OUT_format == "VASP"
            savefile = "STRUCTURES/outstruct_$run.vasp"
            WritePoscar(lattice,composition,FinalPositions,"outstruct")
            println(@sprintf("STRUCTURE %03d EXPORTED IN VASP FORMAT", run))
        else
            println("ERROR: INCORRECT OUTPUT FORMAT")
        end
        mv("outstruct", savefile)
    end
    println("-------------------------------------------------------------------------------------------------")
    println("   END EXPORT DATA")
    println("-------------------------------------------------------------------------------------------------")
end

end